BroadcastSystem/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BroadcastSystem.Models;

namespace BroadcastSystem.Controllers
{
    public class MessagesController : Controller
    {
        private broadcastsystemEntities db = new broadcastsystemEntities();

        //Chen's function 
        public JsonResult GetAll()
        {
            var jsonResult = Json(
                db.Messages.ToList()
                .Where(x => x.IsActived == true)
                .OrderByDescending(x => x.ID),
                JsonRequestBehavior.AllowGet
                );
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;
        }

        // Hayden's function
        public JsonResult GetBroadcasting()
        {
            var jsonResult = Json(
                db.Messages.ToList()
                .Where(x => x.IsActived == true && x.IsBroadcasting == true &&
                    x.To >= DateTime.Now && x.From <= DateTime.Now)
                .OrderByDescending(x => x.ID),
                JsonRequestBehavior.AllowGet
                );
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;
        }

        // GET: Messages no model
        public ActionResult Index()
        {
            return View();
        }

        // GET: Messages/Details/5
        public JsonResult Details(int? id)
        {
            Message message = db.Messages.Find(id);
            return Json(message, JsonRequestBehavior.AllowGet);
        }

        // GET: Messages/Create
        public ActionResult Create()
        {
            ViewBag.AuthorID = new SelectList(db.Authors, "ID", "Username");
            return View();
        }

        // POST: Messages/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,AuthorID,Title,Content,From,To,IsBroadcasting,CreatedOn,CreatedBy,UpdatedOn,UpdatedBy,IsActived")] Message message)
        {
            if (ModelState.IsValid)
            {
                message.CreatedOn = DateTime.Now;
                message.UpdatedOn = DateTime.Now;
                message.IsActived = true;
                message.IsBroadcasting = true;
                db.Messages.Add(message);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AuthorID = new SelectList(db.Authors, "ID", "Username", message.AuthorID);
            return View(message);
        }

        // GET: Messages/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Message message = db.Messages.Find(id);
            if (message == null)
            {
                return HttpNotFound();
            }
            ViewBag.AuthorID = new SelectList(db.Authors, "ID", "Username", message.AuthorID);
            return View(message);
        }

        // POST: Messages/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,AuthorID,Title,Content,From,To,IsBroadcasting,CreatedOn,CreatedBy,UpdatedOn,UpdatedBy,IsActived")] Message message)
        {
            if (ModelState.IsValid)
            {
                message.UpdatedOn = DateTime.Now;
                db.Entry(message).State = EntityState.Modified;
                db.Entry(message).Property(m => m.CreatedOn).IsModified = false;
                db.Entry(message).Property(m => m.IsActived).IsModified = false;
                db.Entry(message).Property(m => m.IsBroadcasting).IsModified = false;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AuthorID = new SelectList(db.Authors, "ID", "Username", message.AuthorID);
            return View(message);
        }

        // GET: Messages/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Message message = db.Messages.Find(id);
            if (message == null)
            {
                return HttpNotFound();
            }
            message.UpdatedOn = DateTime.Now;
            message.IsActived = false;
            db.Entry(message).State = EntityState.Modified;
            db.Entry(message).Property(m => m.CreatedOn).IsModified = false;
            db.Entry(message).Property(m => m.IsBroadcasting).IsModified = false;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public int Broadcast(int? id, bool value)
        {
            if (id == null)
            {
                return 0;
            }
            Message message = db.Messages.Find(id);
            message.UpdatedOn = DateTime.Now;
            message.IsBroadcasting = value;
            db.Entry(message).State = EntityState.Modified;
            db.Entry(message).Property(m => m.CreatedOn).IsModified = false;
            db.Entry(message).Property(m => m.IsActived).IsModified = false;
            db.SaveChanges();
            return 1;
        }

        // POST: Messages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Message message = db.Messages.Find(id);
            db.Messages.Remove(message);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BroadcastSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2017.1.223/styles/kendo.common-material.min.css" />
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2017.1.223/styles/kendo.material.min.css" />
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2017.1.223/styles/kendo.material.mobile.min.css" />

    <script src="https://kendo.cdn.telerik.com/2017.1.223/js/jquery.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2017.1.223/js/kendo.all.min.js"></script>

    <script src="~/Scripts/Site.js"></script>
    <style>
        .form-horizontal .control-label {
            text-align: left;
        }

        #frame {
            width: 800px;
            height: 520px;
            border: none;
            /*-moz-transform: scale(0.2);
            -moz-transform-origin: 0 0;
            -o-transform: scale(0.2);
            -o-transform-origin: 0 0;
            -webkit-transform: scale(0.2);
            -webkit-transform-origin: 0 0;*/
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Broadcast System", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Broadcast", "Index", "Messages")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Broadcast System</p>
        </footer>
    </div>
</body>
</html>